name: Cache

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '* */24 * * *'
jobs:
  cache:
    name: Warm cache
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Warm the cache
        run: |
          tuist cache warm
        env:
          TUIST_CLOUD_TOKEN: ${{ secrets.TUIST_CLOUD_TOKEN }}
