name: uFeatures

on: ["push"]

jobs:
  build-uCore:
    name: Build uCore
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: |
          tuist generate
      - name: Build uCore
        run: |
          make build-core
  test-uCore:
    name: Test uCore
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: |
          tuist generate
      - name: Test uCore
        run: |
          make test-core
  build-uTesting:
    name: Build uTesting
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: |
          tuist generate
      - name: Build uTesting
        run: |
          make build-testing
  build-uFeatures:
    name: Build uFeatures
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: |
          tuist generate
      - name: Build uFeatures
        run: |
          make build-features
  test-uFeatures:
    name: Test uFeatures
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: |
          tuist generate
      - name: Test uFeatures
        run: |
          make test-features
  build-uUI:
    name: Build uUI
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: |
          tuist generate
      - name: Build uUI
        run: |
          make build-ui
  test-uUI:
    name: Test uUI
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: |
          tuist generate
      - name: Test uUI
        run: |
          make test-ui
  build-uHome:
    name: Build uHome
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: |
          tuist generate
      - name: Build uHome
        run: |
          make build-home
  test-uHome:
    name: Test uHome
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: |
          tuist generate
      - name: Test uHome
        run: |
          make test-home
  build-uSearch:
    name: Build uSearch
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: |
          tuist generate
      - name: Build uSearch
        run: |
          make build-search
  test-uSearch:
    name: Test uSearch
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: |
          tuist generate
      - name: Test uSearch
        run: |
          make test-search
  build-app:
    name: Build uSearch
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: |
          tuist generate
      - name: Build App
        run: |
          make build-app
  test-App:
    name: Test App
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: |
          tuist generate
      - name: Test App
        run: |
          make test-app
      
